// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for ListWidgetsParamsScenario.
const (
	NilSlice     ListWidgetsParamsScenario = "nil-slice"
	Ok           ListWidgetsParamsScenario = "ok"
	OmitOptional ListWidgetsParamsScenario = "omit-optional"
)

// Valid indicates whether the value is a known member of the ListWidgetsParamsScenario enum.
func (e ListWidgetsParamsScenario) Valid() bool {
	switch e {
	case NilSlice:
		return true
	case Ok:
		return true
	case OmitOptional:
		return true
	default:
		return false
	}
}

// Widget defines model for Widget.
type Widget struct {
	Id string `json:"id"`

	// Label Optional. A server is free to leave this out; a client must cope with it being absent.
	Label *string `json:"label,omitempty"`
}

// WidgetList defines model for WidgetList.
type WidgetList struct {
	// GeneratedAt Always present.
	GeneratedAt string `json:"generatedAt"`

	// Items Optional, and NOT nullable. Either the key is absent, or its value is an array. `null` is not a legal value here.
	Items *[]Widget `json:"items,omitempty"`
}

// ListWidgetsParams defines parameters for ListWidgets.
type ListWidgetsParams struct {
	// Scenario Which server implementation to exercise.
	Scenario ListWidgetsParamsScenario `form:"scenario" json:"scenario"`
}

// ListWidgetsParamsScenario defines parameters for ListWidgets.
type ListWidgetsParamsScenario string

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"hJNPb9s8DMa/CqH3PbpOtl5W71QMOxQY1suAHtoCZWQmZitLKkUnNYp890Gymwb9g10SQaYkPr/n4bOx",
	"oY/Bk9dkmmeTbEc9luUVtxvSvIoSIokylX1u86+OkUxjkgr7jdlXxuGKXP7SUrLCUTl405jLskBXwzkk",
	"ki0JcIK1EIEGcIRbAu04QRj0OyBYx+QV+iEp2BAJdqwdsMKK2G8AV4m81qZ628C+MkKPAwu1prnOTd4e",
	"asLqnqzmJidNvzh9oGtDngSV2nN9L+Pc7XBMEIU+eb8yrNSnzwFUgL6F35d/wA/O4cpRDT9ZOxLQjuCB",
	"xgxm0ldBEGBNsEU3UNn3gCI41nCXj9/lPR8UEBxt0M2FHQnl3g6t/C+0No35b/Hq8mK2eDH7uz9IKQ+8",
	"I3mM5T3SXM1+HT4gBi05XpWzbgRlP4INXgWt1nChQE+cNOUUpC7sQHcBWl6vSbL/hTbe+MPrL8HIEBFe",
	"t+dMWfTQCq8VMKIo7Dp2BKugHSRuKd14F8ID2CBCVusbnx1kdVnLBAJ+oKILm4FMZbYkaZLxpV7Wywwp",
	"RPIY2TTmtF7Wp6YyEbUrlBe7csOcopKeHCzMJC5a05gcuKu5Jp8T7ElJkmmu32K76th2h0npo6OevJar",
	"Mip6IrGcJpdz/eNAMprKeOxLHC15FA7m2ESVgap5tHNz5Ic+Wxse8kF2J8mxzbJDz3oS5sAeuX0Ystt8",
	"bYrBp2lmvi6X+S/7Sr4Ixxgd29Lv4j5lSc9HL/87j2U2S6zexinihiCsYYZdl6Smoe9Rxpnxy7fpggni",
	"BHkQZxrTqcZmsXDBoutC0ubb8uzM7G/3fwMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
